services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5001:5001"
    volumes:
      - ./app:/app
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"